version: '3'

env:
  NAME: krompir

tasks:
  init:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev

  build:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev

  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - cmake --build --preset=dev -t run-exe

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - ctest --preset=dev

  docs:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t docs
      - cmake --build --preset=dev -t docs-serve

  clean:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t clean

  default:
    cmds:
      - task: run
