name: Update submodules

on:
  schedule: [cron: 0 6 * * 0]
  workflow_dispatch:
  
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        
    - name: Set up git user
      uses: fregante/setup-git-user@v2

    - name: Update submodules
      run: |
        # Make changes
        if git commit -am"Update submodules (automated)

        $(git submodule --quiet foreach \
          'tag="$(git describe --tags --abbrev=0 origin/HEAD)"
          if [ "$(git describe --tags)" != "$tag" ]; then
            git checkout --quiet "$tag"
            echo "$name" "$tag"
          fi')"
        then
          git show --raw
        fi
        
        # Write commit information to file
        git log -1 --pretty=%B > /tmp/commit-msg
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: deps/submodule-update
        title: "[Deps] Automated Submodule Update"
        body-path: /tmp/commit-msg
        assignees: egelja
        reviewers: egelja
